#pragma once

// From glfw3.h
#define AK_MOUSE_BUTTON_1 0
#define AK_MOUSE_BUTTON_2 1
#define AK_MOUSE_BUTTON_3 2
#define AK_MOUSE_BUTTON_4 3
#define AK_MOUSE_BUTTON_5 4
#define AK_MOUSE_BUTTON_6 5
#define AK_MOUSE_BUTTON_7 6
#define AK_MOUSE_BUTTON_8 7
#define AK_MOUSE_BUTTON_LAST AK_MOUSE_BUTTON_8
#define AK_MOUSE_BUTTON_LEFT AK_MOUSE_BUTTON_1
#define AK_MOUSE_BUTTON_RIGHT AK_MOUSE_BUTTON_2
#define AK_MOUSE_BUTTON_MIDDLE AK_MOUSE_BUTTON_3